
version: 0.0
os: linux
files:
   - source: s3://testtrybucket/test-try/SourceArti/2pBLSvm.zip
     destination: ec2://Hello-world-EC2/tmp/test-try-destination
hooks:
  BeforeInstall:
    - location: Scripts/UnzipResourceBundle.sh
    - location: Scripts/UnzipDataBundle.sh
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/MonitorService.sh
      timeout: 3600
      runas: codedeployuser
   

 
